### ISSUE TITLE
filename is too long (>100 characters)

### ISSUE THREAD

**Issue by jmreymond** [jprante/elasticsearch-knapsack#83] opened 2015-09-26 14:20 UTC
my export stops because the filename is too long

file name 'evol/mails/%21%7E%21UENERkVCMDkAAQACAAAAAAAAAAAAAAAAABgAAA
AAAAAA4ujoTBv1WUKt4ty4OdM4jMKAAAAQAAAAThSSMI1xBEanP5qvKo4CLQEAAAAA%40orange.fr/_source' is too long ( > 100 bytes)

If elasticsearch accept it, why elasticsearch-knapsack
 does not ?

**Comment by jprante** [comment] 2015-09-27 13:16
Thanks for the report.

The issue is fixed in new releases:

2.0.0-beta2.1
1.7.2.0
1.6.2.0
1.5.2.1

**Comment by jmreymond** [comment] 2015-09-28 07:36
thanks. It works great

**Closed** 2015-10-12 19:27 UTC
